from enum import Enum

from nw_ai_code_detector.config import OUTPUTS_DIR

MANUAL_REVIEW_SET_SIZE = 200
MANUAL_REVIEW_SEED = 200
MANUAL_REVIEW_MIN_PER_LANGUAGE_DIFFICULTY = 8
SCOREABLE_BATCH_SIZE = 150
SCOREABLE_BATCH_SEED = 15042
SCOREABLE_BATCH_PYTHON_COUNT = 75
SCOREABLE_BATCH_DESCRIPTIVE_COUNT = 25
SCOREABLE_BATCH_DESCRIPTIVE_PYTHON_COUNT = 18
SCOREABLE_BATCH_MIN_PER_LANGUAGE_DIFFICULTY = 15
SCOREABLE_BATCH_MIN_PER_SCORE_TERTILE = 12
LABELS_BACKUP_NAME = "manual_labels.jsonl.bak-before-scoreable-150"
LABELING_OUTPUT_DIR = OUTPUTS_DIR / "labeling"
REVIEW_QUEUE_PATH = LABELING_OUTPUT_DIR / "review_queue.json"
BLIND_RELABEL_QUEUE_PATH = LABELING_OUTPUT_DIR / "blind_python_human_relabel_queue.json"
SINGLE_RELABEL_QUEUE_PATH = LABELING_OUTPUT_DIR / "single_relabel_queue.json"
RELABEL_AUDIT_PATH = LABELING_OUTPUT_DIR / "relabel_audit.jsonl"
MANUAL_LABELS_PATH = OUTPUTS_DIR / "manual_labels.jsonl"
FORBIDDEN_IDENTITY_KEYS = frozenset({"user_id", "email"})


class ManualReviewLabel(str, Enum):
    HUMAN = "HUMAN"
    AI = "AI"
    UNSURE = "UNSURE"
